import 'package:cloud_firestore/cloud_firestore.dart';
import '../models/loyalty_model.dart';

class SeedService {
  final FirebaseFirestore _db = FirebaseFirestore.instance;

  Future<void> seedAll() async {
    await seedCategories();
    await seedBrands();
    await seedProducts();
    await seedBanners();
    await seedCoupons();
    await seedLoyaltyRules();
  }

  Future<void> seedCategories() async {
    final categories = [
      {
        'name': 'Óleo',
        'slug': 'oleo',
        'iconUrl': 'https://picsum.photos/seed/oleo/200/200',
        'description': 'Pintura al óleo de alta calidad para artistas profesionales y aficionados.',
        'displayOrder': 1,
        'isActive': true,
      },
      {
        'name': 'Acuarela',
        'slug': 'acuarela',
        'iconUrl': 'https://picsum.photos/seed/acuarela/200/200',
        'description': 'Acuarelas profesionales en pastillas, tubos y sets completos.',
        'displayOrder': 2,
        'isActive': true,
      },
      {
        'name': 'Dibujo',
        'slug': 'dibujo',
        'iconUrl': 'https://picsum.photos/seed/dibujo/200/200',
        'description': 'Lápices, carboncillo, pasteles y herramientas para dibujo artístico.',
        'displayOrder': 3,
        'isActive': true,
      },
      {
        'name': 'Acrílico',
        'slug': 'acrilico',
        'iconUrl': 'https://picsum.photos/seed/acrilico/200/200',
        'description': 'Pintura acrílica de secado rápido en una amplia gama de colores.',
        'displayOrder': 4,
        'isActive': true,
      },
      {
        'name': 'Pastel',
        'slug': 'pastel',
        'iconUrl': 'https://picsum.photos/seed/pastel/200/200',
        'description': 'Pasteles suaves y duros para técnicas de difuminado y capas.',
        'displayOrder': 5,
        'isActive': true,
      },
      {
        'name': 'Escultura',
        'slug': 'escultura',
        'iconUrl': 'https://picsum.photos/seed/escultura/200/200',
        'description': 'Arcilla, herramientas de modelado y materiales para escultura.',
        'displayOrder': 6,
        'isActive': true,
      },
      {
        'name': 'Grabado',
        'slug': 'grabado',
        'iconUrl': 'https://picsum.photos/seed/grabado/200/200',
        'description': 'Materiales y herramientas para técnicas de grabado y estampación.',
        'displayOrder': 7,
        'isActive': true,
      },
      {
        'name': 'Serigrafía',
        'slug': 'serigrafia',
        'iconUrl': 'https://picsum.photos/seed/serigrafia/200/200',
        'description': 'Equipo y tintas para serigrafía artesanal y profesional.',
        'displayOrder': 8,
        'isActive': true,
      },
    ];

    for (final cat in categories) {
      final doc = _db.collection('categories').doc(cat['slug'] as String);
      await doc.set(cat);
    }
  }

  Future<void> seedBrands() async {
    final brands = [
      {
        'name': 'Winsor & Newton',
        'logoUrl': 'https://firebasestorage.googleapis.com/v0/b/elis-art-supplies.appspot.com/o/brands%2Fwinsor-newton.svg?alt=media',
        'country': 'Reino Unido',
        'description': 'Fabricante premium de pinturas finas desde 1832.',
        'isActive': true,
      },
      {
        'name': 'Faber-Castell',
        'logoUrl': 'https://firebasestorage.googleapis.com/v0/b/elis-art-supplies.appspot.com/o/brands%2Ffaber-castell.svg?alt=media',
        'country': 'Alemania',
        'description': 'Lápices y materiales de dibujo de calidad alemana desde 1761.',
        'isActive': true,
      },
      {
        'name': 'Prismacolor',
        'logoUrl': 'https://firebasestorage.googleapis.com/v0/b/elis-art-supplies.appspot.com/o/brands%2Fprismacolor.svg?alt=media',
        'country': 'Estados Unidos',
        'description': 'Lápices de color premium suaves y vibrantes.',
        'isActive': true,
      },
      {
        'name': 'Liquitex',
        'logoUrl': 'https://firebasestorage.googleapis.com/v0/b/elis-art-supplies.appspot.com/o/brands%2Fliquitex.svg?alt=media',
        'country': 'Estados Unidos',
        'description': 'Pionero en pintura acrílica para artistas desde 1955.',
        'isActive': true,
      },
      {
        'name': 'Schmincke',
        'logoUrl': 'https://firebasestorage.googleapis.com/v0/b/elis-art-supplies.appspot.com/o/brands%2Fschmincke.svg?alt=media',
        'country': 'Alemania',
        'description': 'Fabricante alemán de acuarelas y pasteles de alta calidad.',
        'isActive': true,
      },
      {
        'name': 'Rembrandt',
        'logoUrl': 'https://firebasestorage.googleapis.com/v0/b/elis-art-supplies.appspot.com/o/brands%2Frembrandt.svg?alt=media',
        'country': 'Países Bajos',
        'description': 'Pasteles de nivel profesional con pigmentos ricos.',
        'isActive': true,
      },
      {
        'name': 'DAS',
        'logoUrl': 'https://firebasestorage.googleapis.com/v0/b/elis-art-supplies.appspot.com/o/brands%2Fdas.svg?alt=media',
        'country': 'Italia',
        'description': 'Arcilla para modelar de secado al aire, ideal para escultura.',
        'isActive': true,
      },
      {
        'name': 'Speedball',
        'logoUrl': 'https://firebasestorage.googleapis.com/v0/b/elis-art-supplies.appspot.com/o/brands%2Fspeedball.svg?alt=media',
        'country': 'Estados Unidos',
        'description': 'Materiales para grabado, caligrafía y serigrafía.',
        'isActive': true,
      },
    ];

    for (final brand in brands) {
      final doc = _db.collection('brands').doc();
      await doc.set({...brand, 'brandId': doc.id});
    }
  }

  Future<void> seedProducts() async {
    final products = [
      // Óleo - Winsor & Newton
      {
        'name': 'Set de Óleo Winton 12 colores x 37ml',
        'description': 'Set de iniciación con 12 tubos de 37ml de pintura al óleo Winton de Winsor & Newton. Colores básicos para empezar a pintar al óleo con calidad profesional.',
        'categoryId': 'oleo',
        'categoryName': 'Óleo',
        'brandName': 'Winsor & Newton',
        'technique': 'óleo',
        'skillLevel': 'principiante',
        'price': 850.00,
        'discountPrice': 720.00,
        'stock': 25,
        'sku': 'WNO-12X37',
        'images': ['https://picsum.photos/seed/oleo1/400/400', 'https://picsum.photos/seed/oleo1b/400/400'],
        'dimensions': '25x15x8 cm',
        'weight': '0.8 kg',
        'materials': 'Pigmento, Aceite de linaza',
        'rating': 4.5,
        'reviewCount': 32,
        'isFeatured': true,
        'isActive': true,
        'status': 'offer',
      },
      {
        'name': 'Óleo Profesional Artists 20 colores x 37ml',
        'description': 'Set profesional de 20 tubos de óleo Artists de Winsor & Newton. Pigmentos de alta concentración para resultados excepcionales.',
        'categoryId': 'oleo',
        'categoryName': 'Óleo',
        'brandName': 'Winsor & Newton',
        'technique': 'óleo',
        'skillLevel': 'profesional',
        'price': 2450.00,
        'stock': 10,
        'sku': 'WNO-20X37',
        'images': ['https://picsum.photos/seed/oleo2/400/400', 'https://picsum.photos/seed/oleo2b/400/400'],
        'dimensions': '30x20x10 cm',
        'weight': '1.5 kg',
        'materials': 'Pigmento, Aceite de linaza',
        'rating': 4.8,
        'reviewCount': 18,
        'isFeatured': true,
        'isActive': true,
        'status': 'active',
      },
      {
        'name': 'Lienzo para Óleo 40x50 cm',
        'description': 'Lienzo de algodón de grano medio montado en bastidor de madera. Perfecto para pintura al óleo y acrílico.',
        'categoryId': 'oleo',
        'categoryName': 'Óleo',
        'brandName': 'Winsor & Newton',
        'technique': 'óleo',
        'skillLevel': 'intermedio',
        'price': 180.00,
        'stock': 50,
        'sku': 'WNO-LIEN40X50',
        'images': ['https://picsum.photos/seed/lienzo1/400/400'],
        'dimensions': '40x50x2 cm',
        'weight': '0.4 kg',
        'materials': 'Algodón, Madera de pino',
        'rating': 4.3,
        'reviewCount': 45,
        'isFeatured': false,
        'isActive': true,
        'status': 'active',
      },
      // Acuarela - Schmincke
      {
        'name': 'Acuarela en Pastillas Schmincke 12 colores',
        'description': 'Set de 12 pastillas de acuarela Schmincke Horadam. Colores luminosos y de alta transparencia.',
        'categoryId': 'acuarela',
        'categoryName': 'Acuarela',
        'brandName': 'Schmincke',
        'technique': 'acuarela',
        'skillLevel': 'principiante',
        'price': 690.00,
        'discountPrice': 590.00,
        'stock': 30,
        'sku': 'SCH-A12',
        'images': ['https://picsum.photos/seed/acuarela1/400/400', 'https://picsum.photos/seed/acuarela1b/400/400'],
        'dimensions': '18x10x2 cm',
        'weight': '0.2 kg',
        'materials': 'Pigmento, Goma arábiga',
        'rating': 4.6,
        'reviewCount': 28,
        'isFeatured': true,
        'isActive': true,
        'status': 'offer',
      },
      {
        'name': 'Set Acuarela Tubos 24 colores x 15ml',
        'description': 'Set completo de 24 tubos de acuarela profesional. Pigmentos puros y alta concentración para máxima luminosidad.',
        'categoryId': 'acuarela',
        'categoryName': 'Acuarela',
        'brandName': 'Schmincke',
        'technique': 'acuarela',
        'skillLevel': 'profesional',
        'price': 1800.00,
        'stock': 8,
        'sku': 'SCH-A24T',
        'images': ['https://picsum.photos/seed/acuarela2/400/400'],
        'dimensions': '25x15x5 cm',
        'weight': '0.9 kg',
        'materials': 'Pigmento, Goma arábiga',
        'rating': 4.9,
        'reviewCount': 15,
        'isFeatured': true,
        'isActive': true,
        'status': 'new',
      },
      {
        'name': 'Bloc Acuarela A4 300g 20 hojas',
        'description': 'Bloc de papel para acuarela con grano fino, 300g/m². 20 hojas de papel libre de ácido.',
        'categoryId': 'acuarela',
        'categoryName': 'Acuarela',
        'brandName': 'Schmincke',
        'technique': 'acuarela',
        'skillLevel': 'intermedio',
        'price': 220.00,
        'stock': 40,
        'sku': 'SCH-BL-A4',
        'images': ['https://picsum.photos/seed/blocacuarela/400/400'],
        'dimensions': '30x21x1 cm',
        'weight': '0.35 kg',
        'materials': 'Papel de algodón 100%',
        'rating': 4.4,
        'reviewCount': 37,
        'isFeatured': false,
        'isActive': true,
        'status': 'active',
      },
      // Dibujo - Faber-Castell
      {
        'name': 'Lápices Grafito Faber-Castell 9000 Set 12 piezas',
        'description': 'Set de 12 lápices de grafito de la serie 9000. Durezas variadas desde 6H hasta 6B para todo tipo de dibujo.',
        'categoryId': 'dibujo',
        'categoryName': 'Dibujo',
        'brandName': 'Faber-Castell',
        'technique': 'dibujo',
        'skillLevel': 'principiante',
        'price': 185.00,
        'stock': 100,
        'sku': 'FC-9000-12',
        'images': ['https://picsum.photos/seed/dibujo1/400/400', 'https://picsum.photos/seed/dibujo1b/400/400'],
        'dimensions': '20x8x1.5 cm',
        'weight': '0.15 kg',
        'materials': 'Madera de cedro, Grafito',
        'rating': 4.7,
        'reviewCount': 89,
        'isFeatured': true,
        'isActive': true,
        'status': 'active',
      },
      {
        'name': 'Carboncillo Compresido Set 6 piezas',
        'description': 'Set de 6 barras de carboncillo comprimido en diferentes grosores. Ideal para dibujo artístico y bocetos.',
        'categoryId': 'dibujo',
        'categoryName': 'Dibujo',
        'brandName': 'Faber-Castell',
        'technique': 'dibujo',
        'skillLevel': 'intermedio',
        'price': 120.00,
        'discountPrice': 95.00,
        'stock': 60,
        'sku': 'FC-CARB6',
        'images': ['https://picsum.photos/seed/dibujo2/400/400'],
        'dimensions': '15x10x1 cm',
        'weight': '0.08 kg',
        'materials': 'Carboncillo comprimido',
        'rating': 4.2,
        'reviewCount': 41,
        'isFeatured': false,
        'isActive': true,
        'status': 'offer',
      },
      {
        'name': 'Lápices de Color Polychromos Set 24 colores',
        'description': 'Set de 24 lápices de color Polychromos de Faber-Castell. Resistentes a la luz y alta pigmentación.',
        'categoryId': 'dibujo',
        'categoryName': 'Dibujo',
        'brandName': 'Faber-Castell',
        'technique': 'dibujo',
        'skillLevel': 'profesional',
        'price': 950.00,
        'stock': 20,
        'sku': 'FC-POLY-24',
        'images': ['https://picsum.photos/seed/dibujo3/400/400', 'https://picsum.photos/seed/dibujo3b/400/400'],
        'dimensions': '20x12x2 cm',
        'weight': '0.3 kg',
        'materials': 'Madera de cedro, Pigmento, Cera',
        'rating': 4.8,
        'reviewCount': 56,
        'isFeatured': true,
        'isActive': true,
        'status': 'active',
      },
      // Acrílico - Liquitex
      {
        'name': 'Set Acrílico Liquitex Basics 12 colores x 75ml',
        'description': 'Set de 12 colores acrílicos Liquitex Basics en formato de 75ml. Excelente relación calidad-precio para estudiantes.',
        'categoryId': 'acrilico',
        'categoryName': 'Acrílico',
        'brandName': 'Liquitex',
        'technique': 'acrílico',
        'skillLevel': 'principiante',
        'price': 520.00,
        'discountPrice': 440.00,
        'stock': 35,
        'sku': 'LIQ-B12',
        'images': ['https://picsum.photos/seed/acrilico1/400/400'],
        'dimensions': '25x15x10 cm',
        'weight': '1.2 kg',
        'materials': 'Pigmento, Resina acrílica',
        'rating': 4.4,
        'reviewCount': 63,
        'isFeatured': true,
        'isActive': true,
        'status': 'offer',
      },
      {
        'name': 'Set Acrílico Profesional Liquitex 18 colores x 37ml',
        'description': 'Set profesional de 18 colores acrílicos Liquitex Heavy Body. Pigmentos de alta concentración para obras duraderas.',
        'categoryId': 'acrilico',
        'categoryName': 'Acrílico',
        'brandName': 'Liquitex',
        'technique': 'acrílico',
        'skillLevel': 'profesional',
        'price': 1650.00,
        'stock': 12,
        'sku': 'LIQ-PRO18',
        'images': ['https://picsum.photos/seed/acrilico2/400/400', 'https://picsum.photos/seed/acrilico2b/400/400'],
        'dimensions': '20x12x8 cm',
        'weight': '0.8 kg',
        'materials': 'Pigmento, Resina acrílica',
        'rating': 4.7,
        'reviewCount': 22,
        'isFeatured': true,
        'isActive': true,
        'status': 'new',
      },
      // Pastel - Rembrandt
      {
        'name': 'Pasteles Blandos Rembrandt Set 30 colores',
        'description': 'Set de 30 pasteles blandos Rembrandt de la mejor calidad. Pigmentos puros y alta adherencia.',
        'categoryId': 'pastel',
        'categoryName': 'Pastel',
        'brandName': 'Rembrandt',
        'technique': 'pastel',
        'skillLevel': 'intermedio',
        'price': 780.00,
        'stock': 15,
        'sku': 'REM-P30',
        'images': ['https://picsum.photos/seed/pastel1/400/400'],
        'dimensions': '25x15x3 cm',
        'weight': '0.4 kg',
        'materials': 'Pigmento, Goma, Caolín',
        'rating': 4.6,
        'reviewCount': 19,
        'isFeatured': true,
        'isActive': true,
        'status': 'active',
      },
      {
        'name': 'Papel para Pastel A3 160g 10 hojas',
        'description': 'Papel texturizado especialmente diseñado para pastel. Color marfil, 10 hojas tamaño A3.',
        'categoryId': 'pastel',
        'categoryName': 'Pastel',
        'brandName': 'Rembrandt',
        'technique': 'pastel',
        'skillLevel': 'principiante',
        'price': 95.00,
        'stock': 45,
        'sku': 'REM-PAP-A3',
        'images': ['https://picsum.photos/seed/papelpastel/400/400'],
        'dimensions': '42x30x0.3 cm',
        'weight': '0.25 kg',
        'materials': 'Papel libre de ácido',
        'rating': 4.1,
        'reviewCount': 25,
        'isFeatured': false,
        'isActive': true,
        'status': 'active',
      },
      // Escultura - DAS
      {
        'name': 'Arcilla para Modelar DAS 1kg',
        'description': 'Arcilla de modelado de secado al aire DAS. No necesita horno, se seca naturalmente en 24 horas.',
        'categoryId': 'escultura',
        'categoryName': 'Escultura',
        'brandName': 'DAS',
        'technique': 'escultura',
        'skillLevel': 'principiante',
        'price': 85.00,
        'stock': 80,
        'sku': 'DAS-1KG',
        'images': ['https://picsum.photos/seed/escultura1/400/400'],
        'dimensions': '20x10x5 cm',
        'weight': '1.0 kg',
        'materials': 'Arcilla natural',
        'rating': 4.3,
        'reviewCount': 72,
        'isFeatured': false,
        'isActive': true,
        'status': 'active',
      },
      {
        'name': 'Set Herramientas para Escultura 8 piezas',
        'description': 'Juego de 8 herramientas de modelado en madera y metal. Incluye estecas, espátulas y lazos.',
        'categoryId': 'escultura',
        'categoryName': 'Escultura',
        'brandName': 'DAS',
        'technique': 'escultura',
        'skillLevel': 'intermedio',
        'price': 210.00,
        'stock': 30,
        'sku': 'DAS-TOOL8',
        'images': ['https://picsum.photos/seed/escultura2/400/400'],
        'dimensions': '18x12x3 cm',
        'weight': '0.3 kg',
        'materials': 'Madera de haya, Acero inoxidable',
        'rating': 4.5,
        'reviewCount': 34,
        'isFeatured': true,
        'isActive': true,
        'status': 'active',
      },
      // Grabado - Speedball
      {
        'name': 'Set de Grabado en Linóleo Speedball',
        'description': 'Kit completo de grabado en linóleo con 5 gubias, rodillo y tinta. Perfecto para principiantes.',
        'categoryId': 'grabado',
        'categoryName': 'Grabado',
        'brandName': 'Speedball',
        'technique': 'grabado',
        'skillLevel': 'principiante',
        'price': 350.00,
        'discountPrice': 299.00,
        'stock': 15,
        'sku': 'SPB-LINO',
        'images': ['https://picsum.photos/seed/grabado1/400/400'],
        'dimensions': '25x18x5 cm',
        'weight': '0.6 kg',
        'materials': 'Linóleo, Madera, Acero',
        'rating': 4.4,
        'reviewCount': 12,
        'isFeatured': false,
        'isActive': true,
        'status': 'offer',
      },
      {
        'name': 'Planchas de Linóleo A5 5 piezas',
        'description': 'Lote de 5 planchas de linóleo suave tamaño A5 para grabado y estampación.',
        'categoryId': 'grabado',
        'categoryName': 'Grabado',
        'brandName': 'Speedball',
        'technique': 'grabado',
        'skillLevel': 'principiante',
        'price': 120.00,
        'stock': 40,
        'sku': 'SPB-PLAN5',
        'images': ['https://picsum.photos/seed/grabado2/400/400'],
        'dimensions': '21x15x1 cm',
        'weight': '0.2 kg',
        'materials': 'Linóleo',
        'rating': 4.0,
        'reviewCount': 9,
        'isFeatured': false,
        'isActive': true,
        'status': 'active',
      },
      // Serigrafía - Speedball
      {
        'name': 'Kit Serigrafía Speedball 4 colores',
        'description': 'Kit completo de serigrafía con marco, racleta, 4 tintas base y emulsión. Ideal para empezar.',
        'categoryId': 'serigrafia',
        'categoryName': 'Serigrafía',
        'brandName': 'Speedball',
        'technique': 'serigrafía',
        'skillLevel': 'principiante',
        'price': 890.00,
        'stock': 10,
        'sku': 'SPB-SERI4',
        'images': ['https://picsum.photos/seed/serigrafia1/400/400'],
        'dimensions': '40x30x8 cm',
        'weight': '1.8 kg',
        'materials': 'Madera, Poliéster, Tinta base',
        'rating': 4.5,
        'reviewCount': 8,
        'isFeatured': true,
        'isActive': true,
        'status': 'new',
      },
      {
        'name': 'Tinta para Serigrafía Speedball 250ml Negro',
        'description': 'Tinta profesional para serigrafía a base de agua. Color negro intenso, secado rápido.',
        'categoryId': 'serigrafia',
        'categoryName': 'Serigrafía',
        'brandName': 'Speedball',
        'technique': 'serigrafía',
        'skillLevel': 'intermedio',
        'price': 145.00,
        'stock': 25,
        'sku': 'SPB-TIN250',
        'images': ['https://picsum.photos/seed/serigrafia2/400/400'],
        'dimensions': '10x10x8 cm',
        'weight': '0.35 kg',
        'materials': 'Tinta base agua, Pigmento',
        'rating': 4.2,
        'reviewCount': 14,
        'isFeatured': false,
        'isActive': true,
        'status': 'active',
      },
    ];

    // Need brandId mappings for each brand
    final brandSnapshot = await _db.collection('brands').get();
    final brandMap = <String, String>{};
    for (final doc in brandSnapshot.docs) {
      final name = doc.get('name') as String? ?? '';
      brandMap[name] = doc.id;
    }

    for (final product in products) {
      final doc = _db.collection('products').doc();
      final brandName = product['brandName'] as String;
      final data = {
        ...product,
        'brandId': brandMap[brandName] ?? '',
        'createdAt': FieldValue.serverTimestamp(),
      };
      await doc.set(data);
    }
  }

  Future<void> seedBanners() async {
    final banners = [
      {
        'title': '¡Ofertas de Primavera!',
        'imageUrl': 'https://picsum.photos/seed/banner1/800/400',
        'redirectUrl': '/catalog?offer=true',
        'startDate': Timestamp.fromDate(DateTime(2026, 1, 1)),
        'endDate': Timestamp.fromDate(DateTime(2026, 6, 30)),
        'displayOrder': 1,
        'isActive': true,
        'targetAudience': 'all',
      },
      {
        'title': 'Nuevos Productos Winsor & Newton',
        'imageUrl': 'https://picsum.photos/seed/banner2/800/400',
        'redirectUrl': '/catalog?brand=winsor-newton',
        'startDate': Timestamp.fromDate(DateTime(2026, 1, 1)),
        'endDate': Timestamp.fromDate(DateTime(2026, 12, 31)),
        'displayOrder': 2,
        'isActive': true,
        'targetAudience': 'all',
      },
      {
        'title': 'Talleres de Acuarela - Nivel Básico',
        'imageUrl': 'https://picsum.photos/seed/banner3/800/400',
        'redirectUrl': '/events/acuarela',
        'startDate': Timestamp.fromDate(DateTime(2026, 3, 1)),
        'endDate': Timestamp.fromDate(DateTime(2026, 5, 31)),
        'displayOrder': 3,
        'isActive': true,
        'targetAudience': 'customer',
      },
    ];

    for (final banner in banners) {
      final doc = _db.collection('banners').doc();
      await doc.set(banner);
    }
  }

  Future<void> seedCoupons() async {
    final coupons = [
      {
        'type': 'percentage',
        'value': 10.0,
        'minPurchase': 500.0,
        'maxUses': 100,
        'usedCount': 0,
        'expiresAt': Timestamp.fromDate(DateTime(2026, 12, 31)),
        'applicableCategories': null,
        'applicableBrands': null,
        'isActive': true,
        'createdAt': FieldValue.serverTimestamp(),
      },
      {
        'type': 'percentage',
        'value': 15.0,
        'minPurchase': 1000.0,
        'maxUses': 50,
        'usedCount': 5,
        'expiresAt': Timestamp.fromDate(DateTime(2026, 9, 30)),
        'applicableCategories': ['oleo', 'acrilico'],
        'applicableBrands': null,
        'isActive': true,
        'createdAt': FieldValue.serverTimestamp(),
      },
      {
        'type': 'fixed',
        'value': 200.0,
        'minPurchase': 1500.0,
        'maxUses': 30,
        'usedCount': 2,
        'expiresAt': Timestamp.fromDate(DateTime(2026, 8, 31)),
        'applicableCategories': null,
        'applicableBrands': null,
        'isActive': true,
        'createdAt': FieldValue.serverTimestamp(),
      },
      {
        'type': 'percentage',
        'value': 20.0,
        'minPurchase': 2000.0,
        'maxUses': 20,
        'usedCount': 0,
        'expiresAt': Timestamp.fromDate(DateTime(2026, 6, 30)),
        'applicableCategories': null,
        'applicableBrands': ['Faber-Castell'],
        'isActive': true,
        'createdAt': FieldValue.serverTimestamp(),
      },
    ];

    final codes = ['BIENVENIDO10', 'ARTE15', 'ELI200', 'DIBUJO20'];
    for (var i = 0; i < coupons.length; i++) {
      await _db.collection('coupons').doc(codes[i]).set(coupons[i]);
    }
  }

  Future<void> seedLoyaltyRules() async {
    final rules = LoyaltyRulesModel.defaultRules();
    await _db.collection('loyalty_rules').doc('global').set(rules.toFirestore());
  }
}
