// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBv_qCwsPFca8SvPLgGmIomftclU2fXy24',
    appId: '1:394630544536:web:e0e2a0184a950dd740e4ed',
    messagingSenderId: '394630544536',
    projectId: 'eli-s-art',
    authDomain: 'eli-s-art.firebaseapp.com',
    storageBucket: 'eli-s-art.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcoWQzMWzGggkem5x5ViGTx1WnY1vJQpw',
    appId: '1:394630544536:android:c8f63daf9777ba3440e4ed',
    messagingSenderId: '394630544536',
    projectId: 'eli-s-art',
    storageBucket: 'eli-s-art.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'TU_IOS_API_KEY_AQUI',
    appId: '1:394630544536:ios:XXXXX',
    messagingSenderId: '394630544536',
    projectId: 'eli-s-art',
    storageBucket: 'eli-s-art.firebasestorage.app',
    iosBundleId: 'com.elisartsupplies.elis_art_supplies',
  );
}
